name: flutter_html_view
description: Flutter Plugin to render html, Flutter has no default support to render html so this package helps you to render your html to native widgets
version: 0.5.8
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlView

dependencies:
  flutter:
    sdk: flutter

  #  flutter_custom_tabs: "^0.5.0"
  html: "^0.13.3"
  cached_network_image: "^0.4.2"
  video_player: "^0.6.4"
  cached_network_image: "^0.5.0+1"


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
