name: flutter_html_view
description: Flutter Plugin to render html
version: 0.4.0
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlView

dependencies:
  flutter:
    sdk: flutter

  flutter_custom_tabs: "^0.1.0"
  html: "^0.13.3"
  cached_network_image: "^0.4.0"
  video_player: "^0.5.2"


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"