name: flutter_html_textview
description: Flutter Plugin to render html in textview
version: 0.1.2
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlTextView

dependencies:
  flutter:
    sdk: flutter

  html: "^0.13.3"


environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"